SELECT *
FROM T_DOCUMENT;

SELECT NAME
FROM T_DOCUMENT
WHERE ID = 1;

SELECT ID
FROM T_DOCUMENT;

SELECT *
FROM T_DOCUMENT_FIELD;

SELECT *
FROM T_FIELD_TYPE;

SELECT
  t0.*,
  t1.*
FROM T_TEMPLATE t0
  INNER JOIN T_TEMPLATE_META_INFO t1 ON t0.ID = t1.ID_TEMPLATE;


SELECT (SELECT NEXT VALUE FOR SEQ_DOCUMENT) AS ID;

SELECT t1.ID
FROM T_TEMPLATE t0
  INNER JOIN T_DOCUMENT_FIELD t1 ON t0.ID = t1.ID_DOCUMENT
WHERE t0.ID = ?;


SELECT t1.NAME
FROM T_DOCUMENT_FIELD t0
  INNER JOIN T_FIELD_TYPE t1 ON t0.ID_TYPE = t1.ID
WHERE
  ID = ?
  AND
  ID_TEMPLATE = ?;