SELECT *
FROM T_TEMPLATE;

SELECT NAME FROM T_TEMPLATE WHERE ID = 1;

SELECT ID FROM T_TEMPLATE;

SELECT *
FROM T_TEMPLATE_META_INFO;

SELECT *
FROM T_TYPE;

SELECT
  t0.*,
  t1.*
FROM T_TEMPLATE t0
  INNER JOIN T_TEMPLATE_META_INFO t1 ON t0.ID = t1.ID_TEMPLATE;