SELECT *
FROM T_DOCUMENT;

SELECT *
FROM T_DOCUMENT
WHERE TABLE_NAME = 'T1521753031389';

SELECT *
FROM T1521753031389;

SELECT NAME
FROM T_DOCUMENT
WHERE ID = 1;

SELECT ID
FROM T_DOCUMENT;

SELECT *
FROM T_DOCUMENT_FIELD;

SELECT *
FROM T_FIELD_TYPE;

SELECT
  t0.*,
  t1.*
FROM T_DOCUMENT t0
  INNER JOIN T_DOCUMENT_FIELD t1 ON t0.ID = t1.ID_DOCUMENT;

SELECT
  t0.ID,
  t0.NAME,
  t0.DESCRIPTION,
  t0.ACTIVE,
  t0.KEY,
  t0.COLUMN_NAME,
  t1.NAME AS FIELD_TYPE_NAME,
  t0.LENGTH,
  t0.EMPTY,
  t0.ORDERR,
  t0.USERNAME,
  t0.ADD_DT
FROM T_DOCUMENT_FIELD t0
  INNER JOIN T_DOCUMENT_FIELD_TYPE t1 ON t0.ID_FIELD_TYPE = t1.ID;


SELECT (SELECT NEXT VALUE FOR SEQ_DOCUMENT) AS ID;

SELECT t1.ID
FROM T_DOCUMENT t0
  INNER JOIN T_DOCUMENT_FIELD t1 ON t0.ID = t1.ID_DOCUMENT
WHERE t0.ID = ?;


SELECT t1.NAME
FROM T_DOCUMENT_FIELD t0
  INNER JOIN T_FIELD_TYPE t1 ON t0.ID_TYPE = t1.ID
WHERE
  ID = ?
  AND
  ID_DOCUMENT = ?;